### ISSUE TITLE
Support for glide ?

### ISSUE THREAD

**Issue by l0n3r4n83r** [sdomino/scribble#14]
I tried to add scribble to my code using 
```
glide get github.com/nanobox-io/golang-scribble
```
I am prompted for my GitHub username and password but I get the after providing which I get the following error 
```
[WARN]	Unable to checkout github.com/nanobox-io/golang-scribbl
[ERROR]	Update failed for github.com/nanobox-io/golang-scribbl: Unable to get repository
[ERROR]	Failed to checkout packages: Unable to get repository
```
Can we have this package available through glide as well?

**Comment by sdomino** [comment]
Likely irrelevant as this comment is so late, however, it looks like there may have been a misspelling when trying to add the lib: `github.com/nanobox-io/golang-scribbl` -> `github.com/nanobox-io/golang-scribble` (missing the `e` at the end of `scribble`)
