### ISSUE TITLE
"database"

### ISSUE THREAD

**Issue by camielverdult** [sdomino/scribble#19]
Hi, I love the work but I have a question: Is this really a database? As far as I can read the code, this just opens/reads/writes JSON files.

**Comment by sdomino** [comment]
No, not really a "database" in the traditional sense. It's more of a simple flat file storage system. It's only a "database" in the very loose sense that it "stores data".

**Comment by daetal-us** [comment]
> [A database is an organized collection of data, stored and accessed electronically.][1]

@camielverdult: Yes. absolutely. You could argue this is simply an interface and the filesystem is the database but then which "database" doesn't, eventually, want to persist to disk?

[1]: https://en.wikipedia.org/wiki/Database
